name: main
options:
    bundleIdPrefix: com.vikinglock
targets:
    main:
        type: application
        platform: iOS
        deploymentTarget: "12.0"
        sources:
        - src
        - ../../bento/utils.cpp
        - ../../bento/backend/file/file.mm
        - ../../bento/backend/metal/vao.mm
        - ../../bento/backend/metal/texture.mm
        - ../../bento/backend/metal/metal.mm
        - ../../bento/backend/metal/shader.mm
        - ../../main.cpp
        - Resources
        resources:
        - Resources
        settings:
            OTHER_CPLUSPLUSFLAGS: " -std=c++23 -DUSE_METAL -DIOS -DCONVERT -g -O0 -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_EXTENSIVE -Wno-c++17-extensions"
            OTHER_LDFLAGS: " -framework UIKit -framework Metal -framework MetalKit -framework Foundation -framework AudioToolbox -framework CoreGraphics -framework AVFoundation -framework ImageIO -framework QuartzCore -lshaderconvert"
            PRODUCT_BUNDLE_IDENTIFIER: com.vikinglock.main
            CODE_SIGN_STYLE: Automatic
            DEVELOPMENT_TEAM: "T6JW8VHUK2"
            CODE_SIGN_IDENTITY: "Apple Development"
            GENERATE_INFOPLIST_FILE: YES
            frameworks:
            - UIKit
            - Metal
            - MetalKit
            - Foundation
            - AudioToolbox
            - CoreGraphics
            - AVFoundation
            - ImageIO
            - QuartzCore
        base:
            ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        info:
            path: Info.plist
            properties:
                CFBundleIdentifier: com.vikinglock.main
                CFBundleShortVersionString: "1.0"
                CFBundleVersion: "1"
                UILaunchStoryboardName: LaunchScreen
                UISupportedInterfaceOrientations:
                - UIInterfaceOrientationPortrait
                - UIInterfaceOrientationLandscapeLeft  
                - UIInterfaceOrientationLandscapeRight
            resources:
            - LaunchScreen.storyboard